import React from 'react';
import { BarChart, Bar, XAxis, YAxis, ResponsiveContainer, Cell, Tooltip } from 'recharts';
import { AIInsight } from '../services/types';

interface AIAdvisorProps {
  insight: AIInsight | null;
  loading: boolean;
}

const AIAdvisor: React.FC<AIAdvisorProps> = ({ insight, loading }) => {
  const current7DayForecast = insight?.forecast || 0;
  const isEliteEfficiency = (insight?.breakdown?.energy || 0) < 5;

  const savingsData = [
    { name: 'Current', value: current7DayForecast, color: '#94a3b8' },
    { name: 'Optimized', value: insight?.optimizedForecast || (current7DayForecast * 0.8), color: '#10b981' }
  ];

  const recIcons = ['fa-route', 'fa-bolt-lightning', 'fa-seedling'];

  // Pattern visualization data
  const patternData = insight?.patterns ? [
    { subject: 'Consistency', value: insight.patterns.carbonTrend === 'stable' ? 90 : insight.patterns.carbonTrend === 'decreasing' ? 100 : 60 },
    { subject: 'Efficiency', value: isEliteEfficiency ? 95 : 70 },
    { subject: 'Diversity', value: 75 },
    { subject: 'Frequency', value: insight.patterns.averageDailyDistance > 10 ? 80 : 60 },
    { subject: 'Awareness', value: 70 }
  ] : [];

  return (
    <div className="space-y-8 animate-in fade-in zoom-in-95 duration-500 pt-4 pb-24">
      <div className="relative">
        <div className="absolute inset-0 bg-emerald-500 blur-3xl opacity-10 rounded-full"></div>
        <div className="relative glass p-8 rounded-[2.5rem] text-center border-slate-200 dark:border-white/10 bg-white/50 dark:bg-slate-900/50">
          <div className="w-20 h-20 bg-slate-900 dark:bg-emerald-500 rounded-[2rem] flex items-center justify-center mx-auto mb-6 shadow-xl">
            <i className={`fa-solid fa-brain text-3xl ${loading ? 'text-emerald-400 animate-pulse' : 'text-white'}`}></i>
          </div>
          <h2 className="text-2xl font-black text-slate-800 dark:text-white tracking-tight">AI Advisor</h2>
          {isEliteEfficiency && !loading && (
            <div className="inline-block mt-4 px-4 py-1.5 bg-emerald-500 text-white text-[10px] font-black uppercase tracking-[0.12em] rounded-full shadow-lg">
              <i className="fa-solid fa-crown mr-2"></i> Peak Regional Efficiency
            </div>
          )}
          <p className="text-sm text-slate-500 dark:text-slate-300 font-medium leading-relaxed mt-4 px-4">
            {loading ? "EcoPulse AI is synthesizing localized patterns..." : 
             isEliteEfficiency ? "Excellent. Your current consumption is already at the peak sustainable tier for your region." :
             "Context-aware protocols generated by cross-referencing regional emission benchmarks."}
          </p>
        </div>
      </div>

      {!loading && insight && (
        <>
          {/* Behavioral Patterns Section */}
          {insight.patterns && (
            <div className="glass p-6 rounded-[2.5rem] bg-white dark:bg-slate-900/40">
              <h3 className="text-[11px] font-black text-slate-400 uppercase tracking-[0.16em] mb-6 flex items-center gap-2">
                <i className="fa-solid fa-chart-line"></i>
                Behavioral Pattern Analysis
              </h3>
              
              <div className="grid grid-cols-2 gap-4">
                <div className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-2xl">
                  <div className="text-[11px] font-black text-slate-400 uppercase mb-1">Carbon Trend</div>
                  <div className="flex items-center gap-2">
                    <i className={`fa-solid ${insight.patterns.carbonTrend === 'decreasing' ? 'fa-arrow-down text-emerald-500' : insight.patterns.carbonTrend === 'increasing' ? 'fa-arrow-up text-rose-500' : 'fa-minus text-blue-500'}`}></i>
                    <span className="text-sm font-black text-slate-800 dark:text-white capitalize">
                      {insight.patterns.carbonTrend}
                    </span>
                  </div>
                </div>
                
                <div className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-2xl">
                  <div className="text-[11px] font-black text-slate-400 uppercase mb-1">Avg Daily Distance</div>
                  <div className="text-sm font-black text-slate-800 dark:text-white">
                    {insight.patterns.averageDailyDistance.toFixed(1)} <span className="text-xs text-slate-400">km</span>
                  </div>
                </div>
                
                <div className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-2xl col-span-2">
                  <div className="text-[11px] font-black text-slate-400 uppercase mb-1">Peak Travel Days</div>
                  <div className="flex gap-2 mt-2 flex-wrap">
                    {insight.patterns.peakTravelDays.map(day => (
                      <span key={day} className="px-3 py-1 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 text-[10px] font-black rounded-lg uppercase tracking-[0.1em]">
                        {day}
                      </span>
                    ))}
                  </div>
                </div>
                
                <div className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-2xl col-span-2">
                  <div className="text-[11px] font-black text-slate-400 uppercase mb-1">Most Used Vehicle</div>
                  <div className="flex items-center gap-2">
                    <i className="fa-solid fa-car text-emerald-500"></i>
                    <span className="text-sm font-black text-slate-800 dark:text-white">
                      {insight.patterns.mostUsedVehicle}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          )}

          <div className="glass p-6 rounded-[2.5rem] bg-white dark:bg-slate-900/40">
            <h3 className="text-[11px] font-black text-slate-400 uppercase tracking-[0.16em] mb-6">Regional Benchmarking</h3>
            <div className="h-48 w-full">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={savingsData} margin={{ top: 30, right: 10, left: -20, bottom: 0 }}>
                  <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill: '#94a3b8', fontSize: 10, fontWeight: 800}} />
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: '#1e293b', 
                      border: 'none', 
                      borderRadius: '12px',
                      padding: '8px 12px'
                    }}
                    labelStyle={{ color: '#10b981', fontWeight: 'bold', fontSize: 10 }}
                    itemStyle={{ color: '#fff', fontSize: 12 }}
                    formatter={(value: any) => [`${Number(value).toFixed(1)} kg`, 'CO2']}
                  />
                  <Bar dataKey="value" radius={[12, 12, 12, 12]} barSize={50} label={{ 
                    position: 'top', 
                    fill: '#1e293b',
                    fontSize: 11,
                    fontWeight: 900,
                    formatter: (value: number) => `${value.toFixed(1)} kg`
                  }}>
                    {savingsData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
            
            {/* Legend showing what the bars represent */}
            <div className="grid grid-cols-2 gap-3 mt-6">
              <div className="flex items-center gap-2 p-3 bg-slate-50 dark:bg-slate-800/50 rounded-xl">
                <div className="w-3 h-3 rounded bg-slate-400"></div>
                <span className="text-[11px] font-black text-slate-600 dark:text-slate-300">Your Current Trend</span>
              </div>
              <div className="flex items-center gap-2 p-3 bg-emerald-50 dark:bg-emerald-500/10 rounded-xl">
                <div className="w-3 h-3 rounded bg-emerald-500"></div>
                <span className="text-[11px] font-black text-emerald-600 dark:text-emerald-400">Optimized Target</span>
              </div>
            </div>
          </div>

          <div className="space-y-4">
            <div className="flex items-center justify-between px-1">
               <h3 className="text-[11px] font-black text-slate-400 uppercase tracking-[0.16em]">Personal Protocols</h3>
               <span className={`text-[10px] font-black px-2 py-1 rounded-lg tracking-[0.12em] ${isEliteEfficiency ? 'bg-emerald-500 text-white' : 'bg-emerald-500/10 text-emerald-500'}`}>
                 {isEliteEfficiency ? 'ELITE STATUS' : 'CALIBRATED'}
               </span>
            </div>
            {(insight.recommendations ?? []).map((rec, i) => (
              <div key={i} className="glass p-5 rounded-[2rem] flex items-start gap-5 border-slate-200 dark:border-white/5 hover:bg-white dark:hover:bg-slate-800 transition-all duration-300 group">
                <div className="w-14 h-14 rounded-2xl bg-slate-900 dark:bg-slate-800 text-emerald-500 flex items-center justify-center flex-shrink-0 text-2xl shadow-lg">
                  <i className={`fa-solid ${recIcons[i % recIcons.length]}`}></i>
                </div>
                <div>
                  <h4 className="font-black text-slate-800 dark:text-white text-xs mb-1 uppercase tracking-tight">
                    {isEliteEfficiency ? 'Maintenance Protocol' : `Level ${i+1} Optimization`}
                  </h4>
                  <p className="text-xs text-slate-500 dark:text-slate-300 leading-relaxed font-medium">{rec}</p>
                </div>
              </div>
            ))}
          </div>
        </>
      )}

      {loading && (
        <div className="flex flex-col items-center justify-center py-24">
          <div className="w-12 h-12 border-4 border-emerald-500/20 border-t-emerald-500 rounded-full animate-spin mb-6"></div>
          <p className="text-[11px] font-black text-slate-400 uppercase tracking-[0.16em] animate-pulse"> Analyzing...</p>
        </div>
      )}
    </div>
  );
};

export default AIAdvisor;
